BLOCK: __DESIGN_NAME___dfm

NDM_DATABASE: __PROJECT_PATH__/fc/__DESIGN_NAME__.dlib

TCAD_GRD_FILE: __TCAD_GRD_BST__

MAPPING_FILE: __TLUPLUS_MAP_FILE__

NETLIST_FILE: ../spef/cmin_25c.spef
NETLIST_FORMAT: SPEF
*NETLIST_COMPRESS_COMMAND: gzip -q

OPERATING_TEMPERATURE: 25


MAGNIFICATION_FACTOR:1.0
MAGNIFY_DEVICE_PARAMS:NO
MODE: 400

COUPLING_ABS_THRESHolD: 1e-15

COUPLING_REL_THRESHOLD: 0.01

REDUCTION: NO_EXTRA_LOOPS

NETLIST_INPUT_DRIVERS: YES

NETLIST_CONNECT_OPENS: *

REMOVE_DANGLING_NETS : NO

*NETLIST_MAX_FILE_SIZE: 6.0E+09

*NETLIST_MAX_LINE: 500

*REFERENCE_DIRECTION: vertical

COUPLE_TO_GROUND: NO

EXTRACT_VIA_CAPS: YES

METAL_FILL_POLYGON_HANDLING: FLOATING

NETLIST_NODE_SECTION: YES

REDUCTION: NO_EXTRA_LOOPS

*DP_NETLISTING: NO

POWER_NETS: VDD VSS

SLEEP_TIME_AFTER_FINISH:100


*NUM_CORES : 1

STAR_DIRECTORY: stardir_cmin_25c

SKIP_CELLS: *
